# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "CppSharp.Runtime";
    version = "1.1.5.3168";
    hash = "sha256-pVViQ1RqwH2B/H3yxULpjnVj1FW3XMTVAgRJ6RXqbRg=";
  })
  (fetchNuGet {
    pname = "Cyotek.Drawing.BitmapFont";
    version = "2.0.4";
    hash = "sha256-LiL8navL7WgykWDKY8OWZ7m0EcvYbIXn9l86rBOmwBI=";
  })
  (fetchNuGet {
    pname = "dotnet-mgcb";
    version = "3.8.1.303";
    hash = "sha256-/kLXmvw+A0K7LRDAMEdk9Gqx6HPLUBb55fg5gpsW5Ss=";
  })
  (fetchNuGet {
    pname = "dotnet-mgcb-editor";
    version = "3.8.1.303";
    hash = "sha256-FzVtGmz2lTXeK2DcKr2K/85zV1UULjyPxIlqj+2qvNQ=";
  })
  (fetchNuGet {
    pname = "dotnet-mgcb-editor-linux";
    version = "3.8.1.303";
    hash = "sha256-easOpvlyqdvxCyDN6/NVUBpOyNUWD+hLZ92oHsfL900=";
  })
  (fetchNuGet {
    pname = "dotnet-mgcb-editor-mac";
    version = "3.8.1.303";
    hash = "sha256-S0kcG5mZ8SnwySrwpzNguNzsYvzie9LuZ0JhUUWPsA0=";
  })
  (fetchNuGet {
    pname = "dotnet-mgcb-editor-windows";
    version = "3.8.1.303";
    hash = "sha256-mWCkqY6CyuB/olKxjm0O7QGIKmm46qEe8ZFidOyVIPc=";
  })
  (fetchNuGet {
    pname = "FontStashSharp.Base";
    version = "1.1.9";
    hash = "sha256-Fd9Cc9twPi2xZfISlvoKSknlChW2Aqdoj0DVskPMoek=";
  })
  (fetchNuGet {
    pname = "FontStashSharp.MonoGame";
    version = "1.3.7";
    hash = "sha256-JqWyAnv+fW8LAeFQCiHvjNhuvxVBYHH2DiQnQW5+ZwE=";
  })
  (fetchNuGet {
    pname = "FontStashSharp.Rasterizers.StbTrueTypeSharp";
    version = "1.1.9";
    hash = "sha256-qJ7HevnWeajxKvjjw0OkkKjBrtd76VfP8r6Hj9WKZz4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "7.0.0";
    hash = "sha256-55lsa2QdX1CJn1TpW1vTnkvbGXKCeE9P0O6AkW49LaA=";
  })
  (fetchNuGet {
    pname = "MonoGame.Content.Builder.Task";
    version = "3.8.1.303";
    hash = "sha256-1+vQA2dCRt2n5ArySae3Hpubvm62aOTktp3ywapSKZ8=";
  })
  (fetchNuGet {
    pname = "MonoGame.Framework.DesktopGL";
    version = "3.8.1.303";
    hash = "sha256-zYJwr/Gij755Cj1q30uy55Z6hwSYxKEDNZ0UAadUp4s=";
  })
  (fetchNuGet {
    pname = "NativeFileDialogs.AutoGen";
    version = "1.2.1";
    hash = "sha256-ezWtfTAwwbosn/+U4NyRJY1wv6ZQ8kjE2KiFL91VWJ4=";
  })
  (fetchNuGet {
    pname = "NativeFileDialogs.Net";
    version = "1.2.1";
    hash = "sha256-UtQoc2fl0VANS2gzbFvh+anb+6pQ51++IeD69rOa/8M=";
  })
  (fetchNuGet {
    pname = "NativeFileDialogs.Net.Runtime";
    version = "1.2.1";
    hash = "sha256-rHygKqoEVQyLysc7FiUm/FBOG9FjUeEbSNuVOlACKYM=";
  })
  (fetchNuGet {
    pname = "protobuf-net";
    version = "3.2.26";
    hash = "sha256-C1tvk/KSswIr2hxWK7kR8VKfx90TSeOZkhw/aLshj9U=";
  })
  (fetchNuGet {
    pname = "protobuf-net.Core";
    version = "3.2.26";
    hash = "sha256-vJwiCTQkLzwcXsl8YkDl6oY/SQsL0bmCCM6q9jwaOfM=";
  })
  (fetchNuGet {
    pname = "StbImageSharp";
    version = "2.27.14";
    hash = "sha256-JR9DJ5YR3XioQDqM0ceRgMaYU2WNUVbMaP9crDLugnk=";
  })
  (fetchNuGet {
    pname = "StbTrueTypeSharp";
    version = "1.26.12";
    hash = "sha256-Hau6dELqN1z4+9JbUCwi72C1pJ4TV7arop6BmQnRksw=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "7.0.0";
    hash = "sha256-9an2wbxue2qrtugYES9awshQg+KfJqajhnhs45kQIdk=";
  })
  (fetchNuGet {
    pname = "TextCopy";
    version = "6.2.1";
    hash = "sha256-Lb+e9BwWdRFhxyshIIZAywhDFA5ql3uIV6iQTFUkGUA=";
  })
]
